# Generated by Django 5.2.7 on 2025-11-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0003_student_venue_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_address',
            field=models.EmailField(default='julian.gutierrez04@utrgv.edu', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
