# Generated by Django 5.2.7 on 2025-11-18 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_conflicting_data(apps, schema_editor):
    """
    CLEARS ALL EXISTING STUDENT AND MANAGER DATA AND REMOVES M2M LINKS
    to forcefully allow the schema change in this migration to proceed.
    """
    # Get the model definitions as they exist at this migration step
    Student = apps.get_model('link_up', 'Student')
    try:
        Manager = apps.get_model('link_up', 'Manager')
    except LookupError:
        Manager = None

    Event = apps.get_model('link_up', 'Event')

    # 1. Clear M2M links (resolves foreign key mismatch)
    for event in Event.objects.all():
        event.attendees.clear()

    # 2. Delete all existing Student and Manager records (resolves primary key/ID mismatch)
    Student.objects.all().delete()
    if Manager:
        Manager.objects.all().delete()

# 2. FIND THE 'class Migration' block and ADD the RunPython operation:


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0004_event_email_address'),
    ]

    operations = [
        # ADD THIS LINE AS THE FIRST OPERATION!
        migrations.RunPython(clear_conflicting_data,
                             migrations.RunPython.noop),

        # ... the existing operations (AddField, RemoveField, etc.) that were already here ...
    ]

# class Migration(migrations.Migration):

#     dependencies = [
#         ('auth', '0012_alter_user_first_name_max_length'),
#         ('link_up', '0004_event_email_address'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Manager',
#             fields=[
#                 ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
#                 ('department', models.CharField(blank=True, max_length=100)),
#             ],
#         ),
#         migrations.RemoveField(
#             model_name='student',
#             name='email',
#         ),
#         migrations.RemoveField(
#             model_name='student',
#             name='first_name',
#         ),
#         migrations.RemoveField(
#             model_name='student',
#             name='id',
#         ),
#         migrations.RemoveField(
#             model_name='student',
#             name='last_name',
#         ),
#         migrations.AddField(
#             model_name='student',
#             name='user',
#             field=models.OneToOneField(default='Student', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='event',
#             name='manager',
#             field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='student',
#             name='student_id',
#             field=models.CharField(max_length=8, verbose_name='Student ID'),
#         ),
#     ]
