# Generated by Django 5.2.7 on 2025-11-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0005_manager_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
