# Generated by Django 5.2.7 on 2025-11-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0006_manager_remove_student_email_and_more'),
        ('link_up', '0007_remove_event_attendees'),
    ]

    operations = [
    ]
