# Generated by Django 5.2.7 on 2025-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0008_merge_20251118_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='link_up.student'),
        ),
    ]
