# Generated by Django 5.2.7 on 2025-11-20 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0010_venue_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('computer', 'Computer'), ('room', 'Study Room')], max_length=10)),
                ('resource_id', models.PositiveIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['resource_type', 'resource_id', 'start', 'end'], name='link_up_res_resourc_470840_idx'), models.Index(fields=['user', 'start', 'end'], name='link_up_res_user_id_b38684_idx')],
            },
        ),
    ]
