# Generated by Django 5.2.7 on 2025-12-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_up', '0011_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_name',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events-list/'),
        ),
    ]
